@startuml
class PlaceRoadState {
    + OnPop(location:DigitalCursor) : void
    + OnPush(location:DigitalCursor) : void
    + OnMouseDown(location:DigitalCursor) : void
    + OnMouseEnterTile(location:DigitalCursor) : void
    + OnMouseExitTile(location:DigitalCursor) : void
}
IGridControlState <|-- PlaceRoadState
@enduml
