@startuml
class UncollectedGarbageException {
    + <<readonly>> Garbage : object
    + UncollectedGarbageException(garbage:object, message:string)
}
Exception <|-- UncollectedGarbageException
@enduml
