@startuml
class DashboardMenu {
    - float targetXPos
    - Image heatmapImage
    - HeatMap testMap
    - Start() : void
    - Update() : void
    + ToggleMenuHandler() : void
    + UpdateSpriteFromTexture(Texture2D texture) : void
}
Menu <|-- DashboardMenu
@enduml
