@startuml
enum StreamStatus{
    Success,
    Denied,
    EndOfStream
}

class NodeStream{
    -Buffer : List<NodeController>
    -TilePoints : List<Vector2Int>
    -PointingIndex : int
    -RegisterToTile(position : Vector2Int)
    -DeregisterFromTile(position : Vector2Int)

    +GetCurrent() : NodeController
    +MoveNext() : StreamStatus
}
@enduml